travis:
  secure:
    BINSTAR_TOKEN: A2V1q6z7LdRAzQCfeubfM/ynylkx4W1AUVH6obowQf1AHZoBperNjgwSV8nf8Cy+eInFcpYHc00jlbnwrQ1/lWlp2w8/Of4fhxiO4XG2aUtH02Ake0UV6I51YZnJDzkDgbtJ2byu5hbZWMiI9bRNfYhBcHv3pvEYD3EpBz4UzVB3eTb3rTMBGUkSIJyOsjz3QCarSQeNwJGGhVrEftPImZWCqf0eUw0R+2rnramgtsOoQM471p84tbOSCKYc2QjV57p+Z1TQL4suGPAxPTfSuTpnSgLzDqVzK9tZ6xCQZg9gVhRMxrm2kGtKQkIxFY15oPH4N7+hsy8Uv9zdJc5hVBlXFGwCpXFfCLlL1QsVBE4W2vJoKma7HAlOH5ZNGssvUQM+yoQhDdhV0lHgXVp5uPDsY6bbxSq1xdio9W+3j5rLkWaAd3aQTAMOAl1Mh5iF2LIPIhZqM3aZ9PWJoAFQND+vqu6ahpjIrm7cF4+h5O9rFzQTPr6CS3HiBIjMVxTTOiOcghlnAN/NWf8Ml+UpVKRNQsUPh2Z8Of4x1g2tgNtW+g/PaUaGbiI2tei4O68ymhvIkWLirydYeuc8DuhDLqajoWxSDbijnoP+t/N2WBjaHXXO+FIviTHdODXz8M8LEy1rEZ12m0Dh5ZoMDjqn93NaGg/P3gMucL/bcYqeowY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
