travis:
  secure:
    BINSTAR_TOKEN: D6yBMSIYZo/WH5mPsYAfAeyyIY8RjpWd9D9piT8MyaaO0pXWDSa1g8gKOxaJ124D4qBKzr1+fQBk72mNMeuv8tbCZOxO6kyuYtxENaE8rJW2ONgUpJ1rQDqyKw09nrpgcKGV+dt+MLV7+o1sPcQfs1H11eQgahPUMfv7TmnFp8QtMtp+GJKFgyvX5O3CmIl5ZnpEMeerQi0ULQ+/en1e1C5jqDVlZFnVPXROz5Lko3nwxjMqmccuWtHPFKFFbsfidsfL2K0tC8YgLObwqEuKxowE3MjvJGQk5cyQzMrBw6PhPKud02EoaYbanfEtjC1rtjL7OpY61iv1BV47nfdYnOTHjuxVCD8ruC3MaWZ1/wDSosSp4po3WvdwLuayiVmoi0oeJz38hdne+GLFTQSVhF55hJRnph0INYtK38tyLdX8B7cj84yUlLZ6Hb5wUkvQGY9cqqN+LN2MHL2B7G91VYh6DFrA7+HDHVKNf4BQukZbW/e9cD9DwOAEp8ntCU1HummHcR4m3q4DpPDq5UpZ+nWYlj78X7pOyFSkwRlxAXJB1M+gyi2q2NNChNZlPQ3aD+qOfV9hswjvkikL8aWld+3akchOanZ568+rbAs07jjekEjX1iKR/1ZdqTjCd+F8f2XbtFpfqsvKNR2vP0yIiNZKjMmEJvW2JBdv0XTCv2s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
